[package]
name = "print-rand"
version = "0.1.0"
authors = ["Bryan Hyland <bryan.hyland32@gmail.com>"]
edition = "2021"
license = "GPL-3.0"
description = "Prints a random number."
repository = "https://github.com/bhh32/print-rand"

[dependencies]
rand = "0.9.0"